/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ApplicationController;
import Exception.ModDataException;
import Exception.SearchDataException;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Registration;
import model.Unit;


public class ModRegPanel extends javax.swing.JPanel {

    private Registration updatedReg;
    private ApplicationController app =new ApplicationController();
    private ArrayList<Unit> listUnit;
    private JFrame parents;
    private ButtonListener buttList;
    
    public ModRegPanel(Registration reg) {
        initComponents();
        updatedReg =  reg;
        buttList = new ButtonListener();
        
        try{
            listUnit = app.getUnits();
             for(Unit var: listUnit)
            {
                comboUnit.addItem(var);
            }
        }
        catch(SearchDataException e){
            app.WriteLog(e.getMessage());
            JOptionPane.showMessageDialog(null,"<html>"+e.toString()+"<br>Référez vous au fichier de log pour plus de détails</html>","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            app.WriteLog(e.getMessage());
            JOptionPane.showMessageDialog(null,"<html>Une Erreur inattendue est survenue<br>Référez vous au fichier de log pour plus de détails</html>","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        
        buttValid.addActionListener(buttList);
        buttCancel.addActionListener(buttList);
        setInitValues(reg);
        
    }

    public void setParents(JFrame frame)
    {
        parents = frame;
    }
    public void setInitValues(Registration reg){
        int i;
            
        comboSect.setSelectedItem(reg.getSect().getLib());
        radButtColis.setSelected(reg.getColis());
        comboState.setSelectedItem(reg.getState());
        fieldPrice.setText(""+reg.getPrice());
        fieldPrice.setEnabled(false);
        labPrice.setForeground(Color.gray);
    }
    
    private class ButtonListener implements ActionListener
    {

        @Override
        public void actionPerformed(ActionEvent ae) {
           if(ae.getSource()== buttValid) {
               //ModRegPanel.this.checkValues();
               updatedReg.setColis(radButtColis.isSelected());
               updatedReg.setState((String)comboState.getSelectedItem());
               updatedReg.setSect((String)comboSect.getSelectedItem(),comboUnit.getSelectedItem().toString());
               
               try{
                 app.modRegistration(updatedReg);
               }
               catch(ModDataException e){
                   app.WriteLog(e.getMessage());
                   JOptionPane.showMessageDialog(null,"<html>"+e.toString()+"<br>Référez vous au fichier de log pour plus de détails</html>","error",JOptionPane.ERROR_MESSAGE);
               }
              catch (Exception e) {
                  app.WriteLog(e.getMessage());
                    JOptionPane.showMessageDialog(null,"<html>Une Erreur inattendue est survenue"+"<br>Référez vous au fichier de log pour plus de détails</html>","Erreur",JOptionPane.ERROR_MESSAGE);
               }
               
               parents.dispose();
           }
           if(ae.getSource()==buttCancel)
            parents.dispose();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        labUnit = new javax.swing.JLabel();
        labSect = new javax.swing.JLabel();
        labColis = new javax.swing.JLabel();
        radButtColis = new javax.swing.JRadioButton();
        comboSect = new javax.swing.JComboBox();
        comboUnit = new javax.swing.JComboBox();
        buttValid = new javax.swing.JButton();
        buttCancel = new javax.swing.JButton();
        labState = new javax.swing.JLabel();
        comboState = new javax.swing.JComboBox();
        labPrice = new javax.swing.JLabel();
        fieldPrice = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        labUnit.setText("Unité");

        labSect.setText("Section");

        labColis.setText("Colis envoyé");

        comboSect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Balladins", "Louvetaux", "Eclaireurs", "Pionniers" }));

        buttValid.setText("Valider");

        buttCancel.setText("Annuler");

        labState.setText("Etat inscription");

        comboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En attente", "Acceptée", "Refusée" }));

        labPrice.setText("Prix");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labColis)
                            .addComponent(labSect)
                            .addComponent(labUnit)
                            .addComponent(labState)
                            .addComponent(labPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(buttValid)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboSect, 0, 114, Short.MAX_VALUE)
                        .addComponent(comboUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(buttCancel))
                        .addComponent(radButtColis)
                        .addComponent(comboState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labUnit)
                        .addGap(29, 29, 29)
                        .addComponent(labSect)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labState)
                            .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labColis))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboSect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(radButtColis)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPrice)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttValid)
                    .addComponent(buttCancel))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttCancel;
    private javax.swing.JButton buttValid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboSect;
    private javax.swing.JComboBox comboState;
    private javax.swing.JComboBox comboUnit;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labColis;
    private javax.swing.JLabel labPrice;
    private javax.swing.JLabel labSect;
    private javax.swing.JLabel labState;
    private javax.swing.JLabel labUnit;
    private javax.swing.JRadioButton radButtColis;
    // End of variables declaration//GEN-END:variables
}
