/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ApplicationController;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.table.TableColumn;
import model.Personne;
import model.Registration;
import model.SearchRegModel;
import model.Section;
import model.Unit;


public class SearchRegPanel extends javax.swing.JPanel {

    private ApplicationController app;
    private ButtonListener buttListener;
    private ArrayList<Registration> result;
    private SearchRegModel tableModel;
    public SearchRegPanel() {
        initComponents();
        app = new ApplicationController();
        buttListener = new ButtonListener();
        radButtGroup.add(radSect1);
        radButtGroup.add(radSect2);
        radButtGroup.add(radSect3);
        radButtGroup.add(radSect4);
        
        
        buttVali.addActionListener(buttListener);
        
        
        JComponent editor = new JSpinner.DateEditor(spinDate, "dd/MM/yyyy");
        spinDate.setEditor(editor);
        
    }
    
    private class ButtonListener implements ActionListener
    {

        @Override
        public void actionPerformed(ActionEvent ae) {
            if(ae.getSource()== buttVali)
            {
                String section = null;
                
                
                if(radSect1.isSelected())
                    section=radSect1.getText();
                else if (radSect2.isSelected())
                        section=radSect2.getText();
                else if (radSect3.isSelected())
                    section=radSect3.getText();
                else if (radSect4.isSelected())
                    section=radSect4.getText();
                
                Personne pers = new Personne(fieldName.getText(),fieldFiName.getText());
                Registration reg = new Registration((String)comboUnit.getSelectedItem(),section,pers);
                reg.setColis(radButtColis.isSelected());
                reg.setState((String)comboState.getSelectedItem());
                reg.setCrea((Date)spinDate.getValue());
                
                
                result = app.getReg(reg);
                tableModel = new SearchRegModel(result);
                resultTable.setModel(tableModel);
                
                
                //resultTable.setSize(900,resultTable.getHeight());
                TableColumn column = null;
				for (int i = 0; i < 4; i++) {
				    column = resultTable.getColumnModel().getColumn(i);
				    switch (i) 
				    {	//Unité
				    	case 0 : column.setPreferredWidth(100);
				    		break;
				    	//Section
				    	case 1 : column.setPreferredWidth(50);
			    			break;	
				    	//Etat	
				    	case 2 : column.setPreferredWidth(50);
				    		break;
				    	//Date Création	
				    	case 3 : column.setPreferredWidth(70); 
				    		break;
                                        //Demandeur
                                        case 4 : column.setPreferredWidth(150);
				    		break;
                                        // Responsable
                                        case 5: column.setPreferredWidth(150);
                                            break;
                                        //Adresse
                                        case 6:column.setPreferredWidth(200);
                                            break;
                                       //Tel
                                        case 7: column.setPreferredWidth(50);
                                            break;
                                       //email
                                        case 8: column.setPreferredWidth(80);
                                            break;
                                        case 9: column.setPreferredWidth(20);
                                            break;
                                        default :
                                            column.setPreferredWidth(50);
                                            break;                                            
				    }
				}
                
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radButtGroup = new javax.swing.ButtonGroup();
        labUnit = new javax.swing.JLabel();
        labSect = new javax.swing.JLabel();
        radSect1 = new javax.swing.JRadioButton();
        radSect2 = new javax.swing.JRadioButton();
        radSect3 = new javax.swing.JRadioButton();
        radSect4 = new javax.swing.JRadioButton();
        labName = new javax.swing.JLabel();
        labFiName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldFiName = new javax.swing.JTextField();
        labDate = new javax.swing.JLabel();
        spinDate = new javax.swing.JSpinner();
        labColis = new javax.swing.JLabel();
        labState = new javax.swing.JLabel();
        radButtColis = new javax.swing.JRadioButton();
        comboState = new javax.swing.JComboBox();
        buttVali = new javax.swing.JButton();
        buttCancel = new javax.swing.JButton();
        labResult = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        buttModReg = new javax.swing.JButton();
        buttModPers = new javax.swing.JButton();
        buttModLegal = new javax.swing.JButton();
        comboUnit = new javax.swing.JComboBox();

        labUnit.setText("Unité");

        labSect.setText("Section");

        radSect1.setText("Balladins");

        radSect2.setText("Louvetaux");

        radSect3.setText("Eclaireurs");

        radSect4.setText("Pionniers");

        labName.setText("Nom du demandeur");

        labFiName.setText("Prénom du demandeur");

        labDate.setText("Date d'introduction");

        spinDate.setModel(new javax.swing.SpinnerDateModel());

        labColis.setText("Colis envoyé");

        labState.setText("Etat");

        radButtColis.setText("Oui");

        comboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "En attente", "Acceptée", "Refusée" }));

        buttVali.setText("Valider");

        buttCancel.setText("Annuler");

        labResult.setText("Resultat");

        jScrollPane2.setViewportView(resultTable);

        buttModReg.setText("Modifier Demande");

        buttModPers.setText("Modifier Demandeur");

        buttModLegal.setText("Modifier responsable");

        comboUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner une unité", "NM005 - Scouts et Guides Andenne" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labName)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labColis)
                                        .addComponent(labDate)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radButtColis)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttVali)
                                        .addGap(79, 79, 79)
                                        .addComponent(buttCancel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labFiName)
                                            .addComponent(labState))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fieldFiName)
                                            .addComponent(comboState, 0, 140, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labSect)
                                    .addComponent(labUnit))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radSect1)
                                        .addGap(18, 18, 18)
                                        .addComponent(radSect2)
                                        .addGap(18, 18, 18)
                                        .addComponent(radSect3)
                                        .addGap(18, 18, 18)
                                        .addComponent(radSect4))))
                            .addComponent(labResult, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttModReg)
                .addGap(18, 18, 18)
                .addComponent(buttModPers)
                .addGap(18, 18, 18)
                .addComponent(buttModLegal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUnit)
                    .addComponent(comboUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radSect1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radSect3)
                        .addComponent(radSect4)
                        .addComponent(labSect)
                        .addComponent(radSect2)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFiName)
                            .addComponent(fieldFiName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labState)
                            .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radButtColis)
                            .addComponent(labColis))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttVali)
                            .addComponent(buttCancel))))
                .addGap(8, 8, 8)
                .addComponent(labResult)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttModReg)
                    .addComponent(buttModPers)
                    .addComponent(buttModLegal))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttCancel;
    private javax.swing.JButton buttModLegal;
    private javax.swing.JButton buttModPers;
    private javax.swing.JButton buttModReg;
    private javax.swing.JButton buttVali;
    private javax.swing.JComboBox comboState;
    private javax.swing.JComboBox comboUnit;
    private javax.swing.JTextField fieldFiName;
    private javax.swing.JTextField fieldName;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labColis;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labFiName;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labResult;
    private javax.swing.JLabel labSect;
    private javax.swing.JLabel labState;
    private javax.swing.JLabel labUnit;
    private javax.swing.JRadioButton radButtColis;
    private javax.swing.ButtonGroup radButtGroup;
    private javax.swing.JRadioButton radSect1;
    private javax.swing.JRadioButton radSect2;
    private javax.swing.JRadioButton radSect3;
    private javax.swing.JRadioButton radSect4;
    private javax.swing.JTable resultTable;
    private javax.swing.JSpinner spinDate;
    // End of variables declaration//GEN-END:variables
}
